// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nzin/golang-skeleton/swagger_gen/models"
)

// PutTodoOKCode is the HTTP code returned for type PutTodoOK
const PutTodoOKCode int = 200

/*PutTodoOK OK updated

swagger:response putTodoOK
*/
type PutTodoOK struct {
}

// NewPutTodoOK creates PutTodoOK with default headers values
func NewPutTodoOK() *PutTodoOK {

	return &PutTodoOK{}
}

// WriteResponse to the client
func (o *PutTodoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*PutTodoDefault generic error response

swagger:response putTodoDefault
*/
type PutTodoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutTodoDefault creates PutTodoDefault with default headers values
func NewPutTodoDefault(code int) *PutTodoDefault {
	if code <= 0 {
		code = 500
	}

	return &PutTodoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put todo default response
func (o *PutTodoDefault) WithStatusCode(code int) *PutTodoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put todo default response
func (o *PutTodoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put todo default response
func (o *PutTodoDefault) WithPayload(payload *models.Error) *PutTodoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put todo default response
func (o *PutTodoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTodoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
