// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewPutTodoParams creates a new PutTodoParams object
//
// There are no default values defined in the spec.
func NewPutTodoParams() PutTodoParams {

	return PutTodoParams{}
}

// PutTodoParams contains all the bound params for the put todo operation
// typically these are obtained from a http.Request
//
// swagger:parameters putTodo
type PutTodoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*update a todo
	  Required: true
	  In: body
	*/
	Body PutTodoBody
	/*numeric ID of the todo to get
	  Required: true
	  Minimum: 1
	  In: path
	*/
	TodoID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutTodoParams() beforehand.
func (o *PutTodoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PutTodoBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}

	rTodoID, rhkTodoID, _ := route.Params.GetOK("todoID")
	if err := o.bindTodoID(rTodoID, rhkTodoID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTodoID binds and validates parameter TodoID from path.
func (o *PutTodoParams) bindTodoID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("todoID", "path", "int64", raw)
	}
	o.TodoID = value

	if err := o.validateTodoID(formats); err != nil {
		return err
	}

	return nil
}

// validateTodoID carries on validations for parameter TodoID
func (o *PutTodoParams) validateTodoID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("todoID", "path", o.TodoID, 1, false); err != nil {
		return err
	}

	return nil
}
