swagger: '2.0'
info:
  description: >
    golang-skeleton is a golang REST application skeleton The base path for all
    the APIs is "/api/v1".
  title: golang-skeleton
  version: 1.0.0
tags:
  - name: health
    description: Check if golang-skeleton is healthy
x-tagGroups:
  - name: golang-skeleton Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /health:
    get:
      tags:
        - health
      operationId: getHealth
      description: Check if Flagr is healthy
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  health:
    type: object
    properties:
      status:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
